Repository bioinformatics-ua/dicoogle, pull requests merged in 2022-07, with the labels that each got.

#591 Fix and update OpenAPI specification
  dicoogle_web_api.yaml
Labels: bug, enhancement, chores

#585 [webcore] Update example webplugins
  webcore/README.md
  webcore/examples/TC/document-register-element.js
  webcore/examples/TC/react-0.13.0.js
  webcore/examples/TC/react-dropzone.js
  webcore/examples/TC/reactable.js
  webcore/examples/TC/require.js
  webcore/examples/TC/test-lazy-w-react.html
  webcore/examples/TC/test-query-result-w-react.html
  webcore/examples/TC/test-w-react.html
  webcore/examples/TC/test.html
  webcore/examples/dummy/.gitignore
  webcore/examples/dummy/package-lock.json
  webcore/examples/dummy/package.json
  webcore/examples/react-todo/package-lock.json
  webcore/examples/react-todo/package.json
  webcore/examples/react-todo/src/index.jsx
  webcore/examples/react-todo/webpack.common.js
  webcore/examples/react-todo/webpack.dev.js
  webcore/examples/react-todo/webpack.prod.js
Labels: enhancement, webapp, chores

#592 [webapp] Show URI on image meta-data dump
  dicoogle/src/main/resources/webapp/js/components/search/result/imageView.js
Labels: enhancement, webapp
